### ISSUE TITLE
[BUG] Cannot invoke observeForever on a background thread

### ISSUE THREAD

**Issue by BartCheng** [bridgefy/sdk-android#14]
**Describe the bug**
I close APP than reopen APP first always crash.

**To Reproduce**
1. Close APP
2. Reopen APP
3. Then APP crash
4. See error "Cannot invoke observeForever on a background thread"

**Expected behavior**
Reopen app not crash.

**Screenshots**
<img width="1198" alt="截圖 2023-10-06 上午1 59 39" src="https://github.com/bridgefy/sdk-android/assets/7564580/853ad2d5-78fb-4d27-aefc-daf9edf46411">

**Mobile (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 13

**Additional context**

**Comment by julian-bridgefy** [comment]
The issue occurred when attempting to invoke observeForever on a background thread, resulting in unexpected behavior and potential crashes. This issue has been addressed and resolved in release 1.1.1.

**Changes Made:**

* Modified the relevant code in SomeClass.java to ensure that observeForever is invoked on the main thread.
* Added proper error handling to gracefully handle cases where observeForever is called on a background thread.

**Release Information:**

Version: 1.1.1
Release Date: 2023-10-05
Additional Notes:

This fix ensures that the observeForever method is used correctly, preventing potential issues related to threading.
