### ISSUE TITLE
InternetConnectionRequiredException

### ISSUE THREAD

**Issue by qhd12345** [bridgefy/sdk-android#7]
I'm still experiencing the same issue even after updating the SDK to the production version.
Can not init Bridgefy with onFailToStart:InternetConnectionRequiredException(error=It has not been possible to validate the SDK, check your internet connection or try again, if the problem persists contact the Bridgefy team.)

Code for initialization:
`bridgefy = Bridgefy(MyApplication.context) bridgefy?.init(null,UUID.fromString(BuildConfig.BridgefyKey),PropagationProfile.Standard,delegate)`

I also add Bridgefy API key in manifest
```
<meta-data 
android:name="com.bridgefy.sdk.API_KEY" 
android:value="${bridgefyKey}" 
/>
```

init bridgefy and wait for a while

Device: Galaxy XCover 5
OS: Android 11
bridgefy version: android-sdk:1.0.0

Here is the request for https://prod.sdk.bridgefy.services/bridgefy/v1/login:
```
{
  "hash": "6db268f053a5178295370df800af3de0cdfd4543011c7990faafcfe18a916539",
  "userId": "f76d94f1-1009-40a7-8041-490dabfab322",
  "deviceType": 0,
  "bundleId": "xx.xx.xx",
  "timestamp": "2023-06-29T02:35:59.172Z",
  "version": "1.0.0"
}
```
and getting a status code 401 for response
```
{
  "error": "Hash failed."
}
```

**Comment by julian-bridgefy** [comment]
Thank you for the update, this error occurs under these conditions:
1. The API KEY does not exist.
2. The application ID does not match the ones registered for the API KEY.
3. In the main account, there is no payment method, and it is not possible to validate the license.

If you have an issue with your application ID, please check the consistency and OS for the application ID associated with the API KEY in your main account.

I'm available if this is not useful.

**Comment by harjotbhatia-vakt** [comment]
@julian-bridgefy 
I was getting the same issue, although using older version mentioned in  [Sample Directory](https://github.com/bridgefy/bridgefy-android-sdk-sample)

I changed my appId and now getting, 404 Error App Not Found although the APP Id is correct and App Name is the same.

Any pointers ?

Also, I tried using Bridgefy latest app which is on android but it doesn't seem to work, will using the SDK work ?
